---
title: "Cell Type and Sample Violin Plots Atlantic Salmon"
author: "Sarah Salisbury"
output:
  html_document:
    toc: true
    number_sections: true
---

# Getting Your Data

## Setting up R Environment

### Setup
```{r setup}
# Prevent scientific notation output (e.g., we don't want very small p-values to be output as say 10^-9)
options(scipen=999)
#set seed for reproducibility
set.seed(42) #note that UMAPs use seed of 42, not sure if setting seed here overrides this.
```

### Load Packages

Now load up all of the packages you'll need for this analysis

```{r load packages}
# Load up libraries
library(Seurat) # to run single cell analyses
library(data.table)
library(dplyr)
library(ggplot2)
```

### Load the Seurat object
```{r load Seurat object}
AS.integrated <- readRDS("../../ATLANTIC_SALMON/4_Filter1_Incorporate_Immune_Cell_Substructuring/AS.integrated_filter1_subset.rds")
```

### Set Default Assay

```{r set default assay}
# For performing differential expression after integration, we switch back to the SCT data: https://satijalab.org/seurat/articles/sctransform_v2_vignette.html#perform-integration-using-pearson-residuals-1
DefaultAssay(AS.integrated) <- "SCT"
```

### Set identities to SUBCLUSTER column
```{r set identities}
# Set identity classes to an existing column in meta data
Idents(object = AS.integrated) <- "SUBCLUSTER_MERGED" # the column where we broke down immune and cluster 12 cells
```

```{r}
#https://satijalab.org/seurat/articles/pbmc3k_tutorial.html
new.cluster.ids <- c("1" = "Fibroblast_1",
                     "2" = "Intermediate_Keratinocytes",
                     "3" = "Basal_Keratinocytes",
                     "5" = "Secretory",
                     "6" = "Mucous", 
                     "7" = "Osteoblasts",
                     "8" = "Endothelial",
                     "9" = "Glial_1",
                     "10" = "Superficial_Keratinocytes",
                     "11" = "Red_Blood_Cell",
                     "12" = "Neuronal_1",
                     "13" = "Ltk_cells",
                     "14" = "Fibroblast_2",
                     "16" = "Undifferentiated",
                     "17" = "Glial_2",
                     "18" = "Muscle_cells",
                     "20" = "Neuronal_2",
                     "Dendritic_cells_5" = "Dendritic_cells_5",
                     "Myeloid" = "Myeloid",
                     "T_cells" = "T_cells",
                     "B_cells_10" = "B_cells_10",
                     "Neutrophil_cells_7" = "Neutrophil_cells_7",
                     "Monocyte_11" = "Monocyte_11"
                     )
#https://github.com/satijalab/seurat/issues/3500
AS.integrated <- RenameIdents(AS.integrated, new.cluster.ids)
AS.integrated$CellTypeNames <- Idents(AS.integrated) # save in metadata
```
```{r}
cluster.id.plot.labels <- c("Fibroblast_1" = "Fibroblasts (1)",
                            "Intermediate_Keratinocytes" = "Keratinocytes or Undifferentiated",
                            "Basal_Keratinocytes" = "Basal Keratinocytes",
                            "Endothelial" = "Endothelial", 
                            "Mucous" = "Mucous",
                            "Osteoblasts" = "Osteoblasts",
                            "Secretory" = "Secretory",
                            "Glial_1" = "Glial (1)",
                            "Superficial_Keratinocytes" = "Superficial Keratinocytes",
                            "Red_Blood_Cell" = "Red Blood Cells",
                            "Neuronal_1" = "Neuronal (1)",
                            "Ltk_cells" = "Neural Crest Cells",
                            "Fibroblast_2" = "Fibroblasts (2)",
                            "Undifferentiated" = "Undifferentiated",
                            "Glial_2" = "Glial (2)",
                            "Muscle_cells" = "Muscle",
                            "Neuronal_2" = "Neuronal (2)",
                            "Dendritic_cells_5" = "Dendritic Cells",
                            "Myeloid" = "Macrophages",
                            "T_cells" = "T Cells",
                            "B_cells_10" = "B Cells",
                            "Neutrophil_cells_7" = "Neutrophils",
                            "Monocyte_11" = "Monocyte")
```

```{r}
order_plots <- c("T_cells",
                 "B_cells_10",
                 "Dendritic_cells_5",
                 "Neutrophil_cells_7",
                 "Myeloid",
                 "Monocyte_11",
                 "Superficial_Keratinocytes",
                 "Intermediate_Keratinocytes",
                 "Basal_Keratinocytes",
                 "Fibroblast_1",
                 "Fibroblast_2",
                 "Endothelial",
                 "Secretory",
                 "Mucous",
                 "Osteoblasts",
                 "Red_Blood_Cell",
                 "Muscle_cells",
                 "Ltk_cells",
                 "Neuronal_1",
                 "Neuronal_2",
                 "Glial_1",
                 "Glial_2",
                 "Undifferentiated")

# Don't want to remake factor according to: https://github.com/satijalab/seurat/issues/3500
# Make Identity factor orders
#CO.integrated$CellTypeNames <- factor(CO.integrated$CellTypeNames, levels = order_plots)
#Idents(CO.integrated) <- CO.integrated$CellTypeNames
#orders your cell type names by the order you specified in order_plots
levels(AS.integrated) <- order_plots # note this is ok to do for a Seurat object but not ok for levels in a factor in a column! As the latter will rename all your levels !!!
```


### Load the Differentially Expressed Markers
```{r load markers}
DE_AS <- fread(file = "../DE-AS_filter1_subsetted.txt", sep="\t", stringsAsFactors = FALSE)
#Note that you'll get a warning because no column name for first column, how R fixes it (giving column name "V1" to first column is fine)
```

### Ok let's play
```{r}
# Check how many remaining cells you have
table(AS.integrated$orig.ident)

# How many umi/cell on average
# Taken from: https://www.statology.org/r-mean-by-group/
AS.integrated@meta.data %>%
  group_by(orig.ident) %>%
  summarise_at(vars(nCount_RNA), list(name = mean))

# How many feature/cell on average
AS.integrated@meta.data %>%
  group_by(orig.ident) %>%
  summarise_at(vars(nFeature_RNA), list(name = mean))

# Ok remind me of our samples
unique(AS.integrated@meta.data$orig.ident)

# sample colours
sample.colors <- c(AS_TX_skin = "#3333FF",
                   AS_TA_skin = "#ffffb2",
                   AS_TB_skin ="#fecc5c",
                   AS_TC_skin = "#fd8d3c",
                   AS_TD_skin = "#f03b20",
                   AS_TE_skin = "#bd0026",
                   AS_TX_PV = "#3333FF",
                   #AS_TA_PV = "#ffffb2",
                   #AS_TB_PV ="#fecc5c",
                   AS_TC_PV = "#fd8d3c",
                   AS_TD_PV = "#f03b20",
                   AS_TE_PV = "#bd0026")

#cluster colours
colours_figs <- c("T_cells"  = "darkorchid4",
               "Myeloid" = "magenta2",
               "Dendritic_cells_5" = "orchid1",
               "Neutrophil_cells_7" = "hotpink",
               "Monocyte_11" = "darkmagenta",
               "B_cells_10" = "mediumorchid",
               "Intermediate_Keratinocytes" = "darkgoldenrod",
               "Basal_Keratinocytes" = "darkgoldenrod4",
               "Superficial_Keratinocytes" = "darkgoldenrod2",
               "Fibroblast_1" = "chocolate3",
               "Secretory" = "deepskyblue4",
               "Endothelial" = "deepskyblue",
               "Mucous" = "darkolivegreen",
               "Osteoblasts" = "burlywood1",
               "Red_Blood_Cell" = "firebrick1",
               "Muscle_cells" = "darkred",
               "Ltk_cells" = "lightblue3",
               "Neuronal_1" = "slateblue3",
               "Neuronal_2" = "navy",
               "Glial_1" = "thistle",
               "Glial_2" = "thistle4",
               "Fibroblast_2" = "khaki3",
               "Undifferentiated" = "salmon"
)

cluster.sample.plot.labels <- c(
  "AS_TX_skin" = "Atlantic_Control_skin",
  "AS_TA_skin" = "Atlantic_12h_skin",
  "AS_TB_skin" = "Atlantic_24h_skin",
  "AS_TC_skin" = "Atlantic_36h_skin",
  "AS_TD_skin" = "Atlantic_48h_skin",
  "AS_TE_skin" = "Atlantic_60h_skin",
  "AS_TX_PV" = "Atlantic_Control_fin",
  #"AS_TA_PV" = "Atlantic_12h_fin",
  #"AS_TB_PV" = "Atlantic_24h_fin",
  "AS_TC_PV" = "Atlantic_36h_fin",
  "AS_TD_PV" = "Atlantic_48h_fin",
  "AS_TE_PV" = "Atlantic_60h_fin"
)

order_samples <-c(
  "AS_TX_PV",
  "AS_TX_skin",
  "AS_TA_PV",
  "AS_TA_skin",
  "AS_TB_PV",
  "AS_TB_skin",
  "AS_TC_PV",
  "AS_TC_skin",
  "AS_TD_PV",
  "AS_TD_skin",
  "AS_TE_PV",
  "AS_TE_skin"
)

#change order of orig.ident and make it a factor
AS.integrated$orig.ident <- factor(AS.integrated$orig.ident, levels = order_samples)
```

```{r}
# Plot number of UMIs per sample
plotumispersample <- VlnPlot(object = AS.integrated, features = c("nCount_RNA"), group.by = "orig.ident", pt.size = 0) +
  stat_summary(fun = "mean", #add horizontal bar with mean
               geom = "crossbar",
               width = 0.5,
               colour = "black") +
  scale_fill_manual(values=sample.colors) + #make nice colours
  scale_x_discrete(labels = cluster.sample.plot.labels) + # make nice labels
  theme(legend.position = "none") + # remove legend
  labs(y = "Number of UMIs",
       x = "Sample",
       title = NULL) #remove default main title

#Great now save this plot
png("Samples_umis.png", res=600, width=4200, height=3200)
plotumispersample
dev.off()

# Plot number of features per sample
plotfeaturespersample <- VlnPlot(object = AS.integrated, features = c("nFeature_RNA"), group.by = "orig.ident", pt.size = 0) +
  stat_summary(fun = "mean", #add horizontal bar with mean
               geom = "crossbar",
               width = 0.5,
               colour = "black") +
  scale_fill_manual(values=sample.colors) + #make nice colours
  scale_x_discrete(labels = cluster.sample.plot.labels) + # make nice labels
  theme(legend.position = "none") + # remove legend
  labs(y = "Number of Features",
       x = "Sample",
       title = NULL) #remove default main title

#Great now save this plot
png("Samples_features.png", res=600, width=4200, height=3200)
plotfeaturespersample
dev.off()
```

```{r}
#Generate a plot of the number of UMIs per cluster
plotumispercluster <- VlnPlot(AS.integrated, features = 'nCount_RNA', pt = 0) + # don't show individual cells, pt = 0
  stat_summary(fun = "mean", #add horizontal bar with mean
               geom = "crossbar",
               width = 0.5,
               colour = "black") +
  scale_fill_manual(values=colours_figs) + #make nice colours
  scale_x_discrete(labels = cluster.id.plot.labels) + # make nice labels
  theme(legend.position = "none") + # remove legend
  labs(y = "Number of UMIs",
       x = NULL,
       title = NULL) #remove default main title

VlnPlot(AS.integrated, features = 'nCount_RNA', pt = 0)

#Great now save this plot
png("Clusters_umis.png", res=600, width=4200, height=3200)
plotumispercluster
dev.off()

#Generate a plot of the number of features per cluster
plotfeaturespercluster <- VlnPlot(AS.integrated, features = 'nFeature_RNA', pt = 0) +# don't show individual cells, pt = 0
  stat_summary(fun = "mean", #add horizontal bar with mean
               geom = "crossbar",
               width = 0.5,
               colour = "black") +
  scale_fill_manual(values=colours_figs) + #make nice colours
  scale_x_discrete(labels = cluster.id.plot.labels) + # make nice labels
  theme(legend.position = "none") + # remove legend
  labs(y = "Number of Features",
       x = NULL,
       title = NULL) #remove default main title

#Great now save this plot
png("Clusters_features.png", res=600, width=4200, height=3200)
plotfeaturespercluster
dev.off()
```

```{r}
#Ok so this only keep genes with an adjusted p-value less than 0.05 and generates the top 20 genes for each cluster based on avg_log2FC
markers <- DE_AS %>% dplyr::group_by(cluster) %>% filter(p_val_adj < 0.05) %>% top_n(n = 20, wt = avg_log2FC)
#Ok please note that the first column is a duplicate of the gene column, but there's been a a digit added to the end of each repeated instance of each gene. So if "gene X" appears twice, the second time in the first column it will appear as "gene X2". This is irrelevant to us, so just delete this column.
markers <- markers[,-1]
#now make into a dataframe
markers <- as.data.frame(markers)

#write.csv(markers, "Top20Features.csv")

# Now what I'd like to do is make a violin plot showing expression of these top 20 genes for each cluster in all clusters.

#Ok so first let's find the name of all clusters:
clusters <- unique(markers %>% dplyr::select(cluster) %>% pull(cluster))

# We're going to save several plots in a list so generate an empty list
plot_list_vln_cluster = list()

library(gridExtra) # needed for grid.arrange
library(grid) #needed for textGrob
# for loop?
for (i in 1:length(clusters)) {
  # make list of features to plot for each cluster
  features <- markers %>% dplyr::filter(cluster == clusters[i]) %>% dplyr::select(gene) %>% pull(gene)

  # now plot
  pl1 <- VlnPlot(AS.integrated, features = features, pt.size = 0, assay = "SCT", slot = "data", combine = FALSE) # set pt.size to 0 to remove the points and just see the violins!
  pl2 <- lapply( #https://github.com/satijalab/seurat/issues/1425
    X = pl1,
    FUN = function(p) p + ggplot2::scale_fill_manual(values=colours_figs) + #make nice colours
    ggplot2::scale_x_discrete(labels = cluster.id.plot.labels) +# make nice labels
      theme(legend.position = "none") + # remove legend
    labs(y = NULL,
         x = NULL) 
    )
  n <- length(pl2) #https://stackoverflow.com/questions/10706753/how-do-i-arrange-a-variable-list-of-plots-using-grid-arrange
  nCol <- floor(sqrt(n))
  #pl3 <- do.call("grid.arrange", c(pl2, ncol=nCol))
  
  ggsave(file = paste("Violin_plot_for_cluster_",clusters[i], ".png", sep=""),
         height=24,
         width=24,
         units='in',
         dpi=600, 
         arrangeGrob(grobs = pl2, 
                   ncol = nCol, 
                   left=textGrob("Expression Level",
                                     rot = 90,
                                     gp = gpar(fontsize = 40))))  # add label on left
                     
  #https://stackoverflow.com/questions/39008773/ggplot-how-to-add-common-x-and-y-labels-to-a-grid-of-plots
  #plot_list_vln_cluster[[i]] = pl3 #add the figure to the list
}
```
```{r session info}
sessionInfo()
```
